version: '2'

services:
  uppy:
    image: uppy-server
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
    ports:
      - "3020:3020"
    environment:
      UPPYSERVER_SECRET: ${UPPYSERVER_SECRET}
      UPPYSERVER_DOMAIN: ${UPPYSERVER_DOMAIN}
      UPPYSERVER_DATADIR: ${UPPYSERVER_DATADIR}
      UPPYSERVER_PROTOCOL: ${UPPYSERVER_PROTOCOL}
      VIRTUAL_HOST: ${UPPYSERVER_DOMAIN}
      LETSENCRYPT_HOST: ${UPPYSERVER_DOMAIN}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      UPPYSERVER_GOOGLE_KEY: ${UPPYSERVER_GOOGLE_KEY}
      UPPYSERVER_GOOGLE_SECRET: ${UPPYSERVER_GOOGLE_SECRET}
      UPPYSERVER_INSTAGRAM_KEY: ${UPPYSERVER_INSTAGRAM_KEY}
      UPPYSERVER_INSTAGRAM_SECRET: ${UPPYSERVER_INSTAGRAM_SECRET}
      UPPYSERVER_FACEBOOK_KEY: ${UPPYSERVER_FACEBOOK_KEY}
      UPPYSERVER_FACEBOOK_SECRET: ${UPPYSERVER_FACEBOOK_SECRET}
    networks:
      - default
      - reverseproxy
networks:
  reverseproxy:
      external:
          name: reverseproxy_default
